name: flakka_build
description: Builders for a flakka runtime
repository: https://github.com/flakka-code/flakka_build
version: 0.1.2-alpha.2

environment:
  sdk: "^3.3.0"

dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.9
  build_runner_core: ^7.3.0
  flakka_protobuf_build_types: ^0.2.0
  glob: ^2.1.2
  protobuf: ^3.1.0
  scratch_space: ^1.0.2

dev_dependencies:
  build_test:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
